# for MacOS:

CXX = clang++
CXXOPTS = 
SANITIZE = -fsanitize=address,undefined
CXXTESTOPTS = -g -std=c++11 -Os -Wall $(SANITIZE)
CXXLINKOPTS =
CXXTESTLINKOPTS = -g $(SANITIZE) -Os
THREADOPT = -pthread

# Address sanitizer seems to generate false positives on MacOS/FreeBSD (known issue)
check: export ASAN_OPTIONS=detect_container_overflow=0

-include Makefile.common
