# for FreeBSD

CXX = clang++
CXXOPTS =
SANITIZE = -fsanitize=address,null,return,bounds,alignment
CXXTESTOPTS = -g -std=c++11 -Os -Wall $(SANITIZE)
CXXLINKOPTS = -lrt
CXXTESTLINKOPTS = -g $(SANITIZE)
THREADOPT = -pthread

# Note: "object-size" sanitizer disabled due to https://github.com/llvm/llvm-project/issues/50464

-include Makefile.common
