# for Linux:

CXX = g++
CXXOPTS = 
SANITIZE = -fsanitize=address,undefined
CXXTESTOPTS = -g -std=c++11 -Os -Wall $(SANITIZE)
CXXLINKOPTS =
CXXTESTLINKOPTS = -g $(SANITIZE)
THREADOPT = -pthread

# Makefile will work from this dir or if copied one level up:
-include Makefile.common
-include ../Makefile.common
