# for Linux:

CXX = g++
CXXOPTS = 
SANITIZE = -fsanitize=address,undefined
CXXTESTOPTS = -g -std=c++11 -Os -Wall $(SANITIZE)
CXXLINKOPTS =
CXXTESTLINKOPTS = -g $(SANITIZE)
THREADOPT = -pthread

-include Makefile.common
