# for FreeBSD

CXX = clang++
CXXOPTS =
SANITIZE = -fsanitize=address,null,return,bounds,alignment,object-size
CXXTESTOPTS = -g -std=c++11 -Os -Wall $(SANITIZE)
CXXLINKOPTS = -lrt
CXXTESTLINKOPTS = -g $(SANITIZE)
THREADOPT = -pthread

# Address sanitizer seems to generate false positives on MacOS/FreeBSD (known issue)
check: export ASAN_OPTIONS=detect_container_overflow=0

# Makefile will work from this dir or if copied one level up:
-include Makefile.common
-include ../Makefile.common
